In [1]:
import numpy as np
import pandas as pd

In [70]:
import nltk
import sklearn
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from konlpy.tag import Okt

from nltk.tokenize import WordPunctTokenizer
from nltk.tokenize import sent_tokenize

from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [3]:
text = """다 잊었다는 거짓말
또 해 버렸죠
내 마음에 그대란 사람
없다고 했죠
너무나 쉽게 잊혀졌다고
이젠 남이라고
서툰 내 사랑에 지쳐 떠난 그대
너무 많이 울려서
잡을 용기조차 낼 수 없었죠
미안해요 내 사랑아
다신 나 같은 사람 만나지 마요
혹시 찾아가도 두 번 다시
나를 허락해 주지 마요
그댄 여리고 너무 착해서
싫단 말도 잘 못하는데
많이 부족한 나를 사랑한 그대
이거면 됐어요 더 이상은
그대 불행하지 않도록
나 이쯤에서 없어지는 게
그댈 위한 나의 사랑인 걸요
너무 투명해서 때론 불안했죠
제멋대로 살아온 나를
감당할 수 없을 것 같죠
미안해요 내 사랑아
다신 나 같은 사람 만나지 마요
혹시 찾아가도 두 번 다시
나를 허락해 주지 마요
그댄 여리고 너무 착해서
싫단 말도 잘 못하는데
고마웠어요 나를 사랑해 줘서
나 같은 사람이 두 번 다시
감히 받을 수 없는 사랑
그대 때문에 행복했어요
울지 마요 그대
잘 생각해 봐요
나쁜 일들만 가득했던 우리
다 잊어야 해요
다신 나 같은 사람 만나지 마요
혹시 찾아가도 두 번 다시
나를 허락해 주지 마요
그댄 여리고 너무 착해서
싫단 말도 잘 못하는데
많이 부족한 나를 사랑한 그대
이거면 됐어요
더 이상은 그대 불행하지 않도록
나 이쯤에서 없어지는 게
그댈 위한 나의 사랑인 걸요
"""

In [4]:
# 한글 쪼개기 (토큰화)
okt = Okt()
text = text.replace("\n", " ") # 데이터 정제
text1 = okt.morphs(text)

In [5]:
# 두 글자 이상의 문자들을 선별해서 담아줌
text2 = []
for word in text1:
    if 4 > len(word) > 1: # 조사와 지시대명사 다 날려버림
        text2.append(word)
print(text2)

['거짓말', '버렸죠', '마음', '대란', '사람', '없다고', '했죠', '너무나', '쉽게', '이라고', '서툰', '사랑', '지쳐', '떠난', '그대', '너무', '많이', '울려서', '용기', '조차', '없었죠', '사랑', '다신', '같은', '사람', '만나지', '혹시', '다시', '나를', '허락', '주지', '여리고', '너무', '착해서', '싫단', '하는데', '많이', '부족한', '나를', '사랑', '그대', '됐어요', '이상은', '그대', '않도록', '이쯤', '에서', '사랑', '너무', '때론', '살아온', '나를', '감당', '없을', '같죠', '사랑', '다신', '같은', '사람', '만나지', '혹시', '다시', '나를', '허락', '주지', '여리고', '너무', '착해서', '싫단', '하는데', '나를', '사랑', '줘서', '같은', '사람', '다시', '감히', '받을', '없는', '사랑', '그대', '때문', '그대', '생각', '봐요', '나쁜', '우리', '잊어야', '다신', '같은', '사람', '만나지', '혹시', '다시', '나를', '허락', '주지', '여리고', '너무', '착해서', '싫단', '하는데', '많이', '부족한', '나를', '사랑', '그대', '됐어요', '이상은', '그대', '않도록', '이쯤', '에서', '사랑']


In [6]:
len(text2), len(set(text2))

(114, 54)

In [7]:
# 키를 추가해줌
vocab = {}
for word in text2: # for 문을 돌리면서 처음 만난 단어라면 
    if word not in vocab: 
        vocab[word] = 0 # vocab 이라는 딕셔너리에 key와 value값 넣어준다
    vocab[word] += 1
vocab

{'거짓말': 1,
 '버렸죠': 1,
 '마음': 1,
 '대란': 1,
 '사람': 5,
 '없다고': 1,
 '했죠': 1,
 '너무나': 1,
 '쉽게': 1,
 '이라고': 1,
 '서툰': 1,
 '사랑': 9,
 '지쳐': 1,
 '떠난': 1,
 '그대': 7,
 '너무': 5,
 '많이': 3,
 '울려서': 1,
 '용기': 1,
 '조차': 1,
 '없었죠': 1,
 '다신': 3,
 '같은': 4,
 '만나지': 3,
 '혹시': 3,
 '다시': 4,
 '나를': 7,
 '허락': 3,
 '주지': 3,
 '여리고': 3,
 '착해서': 3,
 '싫단': 3,
 '하는데': 3,
 '부족한': 2,
 '됐어요': 2,
 '이상은': 2,
 '않도록': 2,
 '이쯤': 2,
 '에서': 2,
 '때론': 1,
 '살아온': 1,
 '감당': 1,
 '없을': 1,
 '같죠': 1,
 '줘서': 1,
 '감히': 1,
 '받을': 1,
 '없는': 1,
 '때문': 1,
 '생각': 1,
 '봐요': 1,
 '나쁜': 1,
 '우리': 1,
 '잊어야': 1}

In [8]:
vocab.items()

dict_items([('거짓말', 1), ('버렸죠', 1), ('마음', 1), ('대란', 1), ('사람', 5), ('없다고', 1), ('했죠', 1), ('너무나', 1), ('쉽게', 1), ('이라고', 1), ('서툰', 1), ('사랑', 9), ('지쳐', 1), ('떠난', 1), ('그대', 7), ('너무', 5), ('많이', 3), ('울려서', 1), ('용기', 1), ('조차', 1), ('없었죠', 1), ('다신', 3), ('같은', 4), ('만나지', 3), ('혹시', 3), ('다시', 4), ('나를', 7), ('허락', 3), ('주지', 3), ('여리고', 3), ('착해서', 3), ('싫단', 3), ('하는데', 3), ('부족한', 2), ('됐어요', 2), ('이상은', 2), ('않도록', 2), ('이쯤', 2), ('에서', 2), ('때론', 1), ('살아온', 1), ('감당', 1), ('없을', 1), ('같죠', 1), ('줘서', 1), ('감히', 1), ('받을', 1), ('없는', 1), ('때문', 1), ('생각', 1), ('봐요', 1), ('나쁜', 1), ('우리', 1), ('잊어야', 1)])

In [9]:
# 정렬의 기준을 정한다
vocab_sorted = sorted(vocab.items(), key = lambda x:x[1], reverse=True)
vocab_sorted

[('사랑', 9),
 ('그대', 7),
 ('나를', 7),
 ('사람', 5),
 ('너무', 5),
 ('같은', 4),
 ('다시', 4),
 ('많이', 3),
 ('다신', 3),
 ('만나지', 3),
 ('혹시', 3),
 ('허락', 3),
 ('주지', 3),
 ('여리고', 3),
 ('착해서', 3),
 ('싫단', 3),
 ('하는데', 3),
 ('부족한', 2),
 ('됐어요', 2),
 ('이상은', 2),
 ('않도록', 2),
 ('이쯤', 2),
 ('에서', 2),
 ('거짓말', 1),
 ('버렸죠', 1),
 ('마음', 1),
 ('대란', 1),
 ('없다고', 1),
 ('했죠', 1),
 ('너무나', 1),
 ('쉽게', 1),
 ('이라고', 1),
 ('서툰', 1),
 ('지쳐', 1),
 ('떠난', 1),
 ('울려서', 1),
 ('용기', 1),
 ('조차', 1),
 ('없었죠', 1),
 ('때론', 1),
 ('살아온', 1),
 ('감당', 1),
 ('없을', 1),
 ('같죠', 1),
 ('줘서', 1),
 ('감히', 1),
 ('받을', 1),
 ('없는', 1),
 ('때문', 1),
 ('생각', 1),
 ('봐요', 1),
 ('나쁜', 1),
 ('우리', 1),
 ('잊어야', 1)]

In [10]:
# 빈도수가 높은 단어만 선별 (2개 이상)
word_to_index = {}
i = 0
for (word, freq) in vocab_sorted: # 워드, 빈도수가 vocab_sorted 여기에서 높은거 추출
    if freq > 1: # 2번 이상 반복되는 것들을 순서대로 레이블 인코딩
        i += 1
        word_to_index[word] = i
word_to_index

{'사랑': 1,
 '그대': 2,
 '나를': 3,
 '사람': 4,
 '너무': 5,
 '같은': 6,
 '다시': 7,
 '많이': 8,
 '다신': 9,
 '만나지': 10,
 '혹시': 11,
 '허락': 12,
 '주지': 13,
 '여리고': 14,
 '착해서': 15,
 '싫단': 16,
 '하는데': 17,
 '부족한': 18,
 '됐어요': 19,
 '이상은': 20,
 '않도록': 21,
 '이쯤': 22,
 '에서': 23}

In [11]:
# `말뭉치(Corpus)` : 언어학에서 (여러 언어의) 텍스트 집합
# 여기까지의 과정이 아래와 같은 말뭉치를 직접 만들어 보는 과정
"""
 ('사랑', 9),
 ('그대', 7),
 ('나를', 7),
 ('사람', 5),
 ('너무', 5),
"""

"\n ('사랑', 9),\n ('그대', 7),\n ('나를', 7),\n ('사람', 5),\n ('너무', 5),\n"

In [12]:
# 5위 밖의 단어들 세기
vocab_size=5
word_freq_cut = [ word for word, index in word_to_index.items() if index >=vocab_size + 1]
word_freq_cut

['같은',
 '다시',
 '많이',
 '다신',
 '만나지',
 '혹시',
 '허락',
 '주지',
 '여리고',
 '착해서',
 '싫단',
 '하는데',
 '부족한',
 '됐어요',
 '이상은',
 '않도록',
 '이쯤',
 '에서']

In [13]:
# 말뭉치에서 빈도 수 5위까지 남기기
print(word_to_index)
for w in word_freq_cut:
    del word_to_index[w]
print(word_to_index)

{'사랑': 1, '그대': 2, '나를': 3, '사람': 4, '너무': 5, '같은': 6, '다시': 7, '많이': 8, '다신': 9, '만나지': 10, '혹시': 11, '허락': 12, '주지': 13, '여리고': 14, '착해서': 15, '싫단': 16, '하는데': 17, '부족한': 18, '됐어요': 19, '이상은': 20, '않도록': 21, '이쯤': 22, '에서': 23}
{'사랑': 1, '그대': 2, '나를': 3, '사람': 4, '너무': 5}


In [14]:
word_to_index["기타"] = len(word_to_index) + 1
print(word_to_index)

{'사랑': 1, '그대': 2, '나를': 3, '사람': 4, '너무': 5, '기타': 6}


In [15]:
word_to_index["사랑"]

1

In [16]:
word_to_index["그대"]

2

In [17]:
encoded_sentences = [] # 자연어가사->숫자 text1
for word in text1:
    try:
        encoded_sentences.append(word_to_index[word])
    except:
        encoded_sentences.append(word_to_index["기타"])
encoded_sentences

[6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 1,
 6,
 6,
 6,
 2,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 1,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 1,
 6,
 2,
 6,
 6,
 6,
 6,
 6,
 6,
 2,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 1,
 6,
 6,
 6,
 5,
 6,
 6,
 6,
 6,
 6,
 3,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 1,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 1,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 1,
 2,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 2,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 1,
 6,
 2,
 6,
 6,
 6,
 6,
 6,
 6,
 2,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 1,
 6,
 6,
 6]

In [18]:
sub_list = list(zip(text1, encoded_sentences))
sub_list

[('다', 6),
 ('잊었다는', 6),
 ('거짓말', 6),
 ('또', 6),
 ('해', 6),
 ('버렸죠', 6),
 ('내', 6),
 ('마음', 6),
 ('에', 6),
 ('그', 6),
 ('대란', 6),
 ('사람', 4),
 ('없다고', 6),
 ('했죠', 6),
 ('너무나', 6),
 ('쉽게', 6),
 ('잊혀졌다고', 6),
 ('이', 6),
 ('젠', 6),
 ('남', 6),
 ('이라고', 6),
 ('서툰', 6),
 ('내', 6),
 ('사랑', 1),
 ('에', 6),
 ('지쳐', 6),
 ('떠난', 6),
 ('그대', 2),
 ('너무', 5),
 ('많이', 6),
 ('울려서', 6),
 ('잡', 6),
 ('을', 6),
 ('용기', 6),
 ('조차', 6),
 ('낼', 6),
 ('수', 6),
 ('없었죠', 6),
 ('미안해요', 6),
 ('내', 6),
 ('사랑', 1),
 ('아', 6),
 ('다신', 6),
 ('나', 6),
 ('같은', 6),
 ('사람', 4),
 ('만나지', 6),
 ('마', 6),
 ('요', 6),
 ('혹시', 6),
 ('찾아가도', 6),
 ('두', 6),
 ('번', 6),
 ('다시', 6),
 ('나를', 3),
 ('허락', 6),
 ('해', 6),
 ('주지', 6),
 ('마', 6),
 ('요', 6),
 ('그', 6),
 ('댄', 6),
 ('여리고', 6),
 ('너무', 5),
 ('착해서', 6),
 ('싫단', 6),
 ('말', 6),
 ('도', 6),
 ('잘', 6),
 ('못', 6),
 ('하는데', 6),
 ('많이', 6),
 ('부족한', 6),
 ('나를', 3),
 ('사랑', 1),
 ('한', 6),
 ('그대', 2),
 ('이', 6),
 ('거', 6),
 ('면', 6),
 ('됐어요', 6),
 ('더', 6),
 ('이상은', 6),
 ('그대', 2),
 ('불행

In [19]:
# 텐서플로 토크나이저
from tensorflow.keras.preprocessing.text import Tokenizer

In [20]:
text = [['다', '잊었다는', '거짓말'],
          ['또', '해', '버렸죠'],
          [],
          ['내', '마음', '에'],
          ['그'], ['대란'], ['사람'],
          ['없다고', '했죠']]

In [21]:
tokenizer = Tokenizer()

In [22]:
tokenizer.fit_on_texts(text)

In [23]:
tokenizer.word_index

{'다': 1,
 '잊었다는': 2,
 '거짓말': 3,
 '또': 4,
 '해': 5,
 '버렸죠': 6,
 '내': 7,
 '마음': 8,
 '에': 9,
 '그': 10,
 '대란': 11,
 '사람': 12,
 '없다고': 13,
 '했죠': 14}

In [24]:
tokenizer.word_counts

OrderedDict([('다', 1),
             ('잊었다는', 1),
             ('거짓말', 1),
             ('또', 1),
             ('해', 1),
             ('버렸죠', 1),
             ('내', 1),
             ('마음', 1),
             ('에', 1),
             ('그', 1),
             ('대란', 1),
             ('사람', 1),
             ('없다고', 1),
             ('했죠', 1)])

In [25]:
tokenizer.texts_to_sequences(text)

[[1, 2, 3], [4, 5, 6], [], [7, 8, 9], [10], [11], [12], [13, 14]]

In [26]:
vocab_size = 5
tok = Tokenizer(num_words = vocab_size + 1)
tok.fit_on_texts(text)

In [27]:
tok.word_index

{'다': 1,
 '잊었다는': 2,
 '거짓말': 3,
 '또': 4,
 '해': 5,
 '버렸죠': 6,
 '내': 7,
 '마음': 8,
 '에': 9,
 '그': 10,
 '대란': 11,
 '사람': 12,
 '없다고': 13,
 '했죠': 14}

In [28]:
words_freq_cut = [word for word, index in tokenizer.word_index.items()
                         if index >= vocab_size + 1]
words_freq_cut

['버렸죠', '내', '마음', '에', '그', '대란', '사람', '없다고', '했죠']

In [29]:
for word in words_freq_cut:
    del tok.word_index[word]
    del tok.word_counts[word]
print(tok.word_index)
print(tok.word_counts)
print(tok.texts_to_sequences(text))

{'다': 1, '잊었다는': 2, '거짓말': 3, '또': 4, '해': 5}
OrderedDict([('다', 1), ('잊었다는', 1), ('거짓말', 1), ('또', 1), ('해', 1)])
[[1, 2, 3], [4, 5], [], [], [], [], [], []]


In [30]:
import konlpy
konlpy.__version__

'0.6.0'

In [34]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [35]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text)
enc = tokenizer.texts_to_sequences(text)
enc

[[1, 2, 3], [4, 5, 6], [], [7, 8, 9], [10], [11], [12], [13, 14]]

In [36]:
padded = pad_sequences(enc)
padded

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  0,  0],
       [ 7,  8,  9],
       [ 0,  0, 10],
       [ 0,  0, 11],
       [ 0,  0, 12],
       [ 0, 13, 14]])

In [37]:
padded_post = pad_sequences(enc, padding="post")
padded_post

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  0,  0],
       [ 7,  8,  9],
       [10,  0,  0],
       [11,  0,  0],
       [12,  0,  0],
       [13, 14,  0]])

In [ ]:
# one hot encoding vs. label encoding

In [32]:
items = ["남자", "여자", "여자", "남자", "여자"]

In [33]:
from sklearn.preprocessing import LabelEncoder

In [38]:
le = LabelEncoder()
le.fit_transform(items)

array([0, 1, 1, 0, 1], dtype=int64)

In [39]:
# 판다스 : get_dummy, sklearn:one hot encoder, tf, keras 등으로 인코딩 방법 접근할 수 있었음.

In [41]:
text = "나는 자연어 처리를 배우는 거겠지. 자연어 처리는 어렵지 않았으면 좋겠어"
text

'나는 자연어 처리를 배우는 거겠지. 자연어 처리는 어렵지 않았으면 좋겠어'

In [43]:
# 케라스 모듈을 통한 인코딩
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

In [44]:
tok = Tokenizer()
tok.fit_on_texts({text})
print(tok.word_index)

{'자연어': 1, '나는': 2, '처리를': 3, '배우는': 4, '거겠지': 5, '처리는': 6, '어렵지': 7, '않았으면': 8, '좋겠어': 9}


In [46]:
sub_text = "나는 어렵지 않기를 바래"
# tok에 서브 텍스트 추가
enc1 = tok.texts_to_sequences([sub_text])[0]
enc1

[2, 7]

In [47]:
ohe1 = to_categorical(enc1)
ohe1

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [49]:
#one hot encoding 만들기
X = ["b", "r", "r", "g", "g"] # 옷 색깔
y = [0, 1, 1, 0, 0] # 구조 여부

df1 = pd.DataFrame({"X": X, "y": y})
df1

X  y
0  b  0
1  r  1
2  r  1
3  g  0
4  g  0

In [50]:
pd.get_dummies(df1["X"])

b  g  r
0  1  0  0
1  0  0  1
2  0  0  1
3  0  1  0
4  0  1  0

In [51]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
# 희소행렬 형태로 출력해야 나옴
ohe.fit_transform(df1)

# 이 경우 인코딩한 레이블이 뭔지 볼 수 없어서 아쉬움.

C:\Users\user\anaconda3\envs\sesac_se\lib\site-packages\sklearn\preprocessing\_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])

In [ ]:
# 언어 모델
# 음성 : 주파수 분석 -> 단어
# 아버지가 방에 들어가신다 -> 아버지 가방에 들어가신다, 아버지가 방에 돌아가신다
# 오타 교정, 음성 인식 교정 -> 추천/
# 자기야 잘 잤어? 오늘도 힘내자 -> 자기(야, 도, 눈), 자기야(잘, 우리, ...), 자기야 잘 (잤어? 나와?)
# 검색어 자동 완성