In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [24]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a2 = a[np.newaxis,:]
a2

array([[0, 1, 2, 3, 4, 5]])

In [5]:
a2.shape

(1, 6)

In [10]:
a = np.array(['1', 2, 3, 4, 5, 6])

In [16]:
a.dtype
# 뒤에 괄호가 붙지 않으면 속성이다. 변수 값을 선언하는 것

dtype('<U11')

In [15]:
a.ndim

1

In [17]:
a.shape

(6,)

In [26]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [27]:
a.dtype

dtype('int32')

In [28]:
a.ndim

2

In [29]:
a.shape

(3, 4)

In [30]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
a[0]

array([1, 2, 3, 4])

In [33]:
a[0,3]

4

In [34]:
a[:,3]

array([ 4,  8, 12])

In [35]:
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
np.array([[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [37]:
np.array([[[1, 2], [3, 4], [5, 6], [4, 5]], [[1, 2], [3, 4], [5, 6]]])

C:\Users\user\AppData\Local\Temp\ipykernel_432\3130613494.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[[1, 2], [3, 4], [5, 6], [4, 5]], [[1, 2], [3, 4], [5, 6]]])


array([list([[1, 2], [3, 4], [5, 6], [4, 5]]),
       list([[1, 2], [3, 4], [5, 6]])], dtype=object)

In [38]:
np.array([[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [42]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.zeros((2, 3), dtype=np.int)

C:\Users\user\AppData\Local\Temp\ipykernel_432\1103946689.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((2, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0]])

In [43]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.empty((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [46]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [51]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [50]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
np.sort(a, axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
np.sort(a, axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
x = np.array([3, 1, 2])

In [57]:
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [58]:
np.argmax(x)

0

In [59]:
x = np.array([[0, 3], [2, 2]])

In [63]:
x

array([[0, 3],
       [2, 2]])

In [60]:
np.argsort(x, axis=-1)

array([[0, 1],
       [0, 1]], dtype=int64)

In [61]:
np.argsort(x, axis=1)

array([[0, 1],
       [0, 1]], dtype=int64)

In [62]:
np.argsort(x, axis=0)

array([[0, 1],
       [1, 0]], dtype=int64)

In [64]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [65]:
np.sort(arr)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [66]:
a = np.array([[1, 4], [3, 1]])

In [69]:
a

array([[1, 4],
       [3, 1]])

In [67]:
np.sort(a, axis=1)

array([[1, 4],
       [1, 3]])

In [68]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [70]:
np.sort(a, axis=-1)

array([[1, 4],
       [1, 3]])

In [75]:
a = np.array([[1, 2, 3, 4]])
b = np.array([[5, 6, 7, 8]])

In [76]:
np.concatenate((a, b), axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [78]:
a = np.array([[[1, 2, 3, 4]]])
b = np.array([[[5, 6, 7, 8]]])

In [79]:
np.concatenate((a, b), axis=0)

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [80]:
np.concatenate((a, b), axis=1)

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [81]:
np.concatenate((a, b), axis=2)

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [82]:
a.ndim

3

In [83]:
a.shape

(1, 1, 4)

In [86]:
np.concatenate((a, b), axis=0).shape

(2, 1, 4)

In [84]:
a.size

4

In [87]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [88]:
a.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [89]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
a = np.array([1, 2, 3, 4, 5, 6])

In [92]:
a.shape

(6,)

In [94]:
a2[np.newaxis,:]

array([[[0, 1, 2, 3, 4, 5]]])

In [95]:
a2.shape

(1, 6)

In [96]:
a3 = a[:,np.newaxis]

In [97]:
a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [99]:
a3.shape

(6, 1)

In [100]:
a

array([1, 2, 3, 4, 5, 6])

In [101]:
b = np.expand_dims(a, axis=0)

In [102]:
b

array([[1, 2, 3, 4, 5, 6]])

In [103]:
np.expand_dims(a3, axis=0)

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

In [104]:
a3.shape

(6, 1)

In [105]:
a4 = np.expand_dims(a3, axis=0)

In [106]:
a4.shape

(1, 6, 1)

In [108]:
a4 = np.expand_dims(a3,axis=1)
a4.shape

(6, 1, 1)

In [109]:
a4

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [111]:
aa = a3.reshape((3, 2))
aa

array([[1, 2],
       [3, 4],
       [5, 6]])

In [112]:
a4 = np.expand_dims(aa, axis=0)
a4.shape

(1, 3, 2)

In [113]:
a4 = np.expand_dims(aa, axis=1)
a4.shape

(3, 1, 2)

In [114]:
a4 = np.expand_dims(aa, axis=2)
a4.shape

(3, 2, 1)

In [115]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [116]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [118]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [119]:
a[(a>2) & (a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
a[(a>5)|(a==5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [121]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [123]:
b = np.nonzero(a<5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [124]:
zip(b[0],b[1])

In [125]:
list(zip(b[0],b[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [126]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [129]:
arr1[0]=14
a

array([ 1,  2,  3, 14,  5,  6,  7,  8,  9, 10])

In [130]:
arr1

array([14,  5,  6,  7,  8])

In [131]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [132]:
np.concatenate((a1,a2), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [133]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
a1 = np.array([[1, 1],
               [2, 2], [3, 3]])

a2 = np.array([[3, 3],
               [4, 4]])

In [201]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [135]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [203]:
np.hsplit(x, (3, -2))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20, 21, 22]]),
 array([[11, 12],
        [23, 24]])]

In [137]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [139]:
data

array([1, 2])

In [138]:
ones

array([1, 1])

In [140]:
data + ones

array([2, 3])

In [141]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [142]:
b = np.array([[1, 1], [2, 2]])

In [145]:
b.sum(0)

array([3, 3])

In [146]:
b.sum(1)

array([2, 4])

In [147]:
data = np.array([1.0, 2.0])
data

array([1., 2.])

In [149]:
data * 1.6

array([1.6, 3.2])

In [150]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [152]:
c=np.array([8])

In [153]:
a*c

array([[  0.,   0.,   0.],
       [ 80.,  80.,  80.],
       [160., 160., 160.],
       [240., 240., 240.]])

In [161]:
rng = np.random.default_rng(1)

In [162]:
rng.random(3) 

array([0.51182162, 0.9504637 , 0.14415961])

In [163]:
rng.integers(1, 5, endpoint=True)

5

In [166]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [169]:
np.unique(a, return_index=True, return_inverse=True, return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64),
 array([0, 0, 1, 2, 3, 4, 5, 6, 1, 2, 0, 3, 7, 8, 9], dtype=int64),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

In [170]:
data = np.arange(1, 7).reshape(2, 3)
data

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
data.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [172]:
data.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [174]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [175]:
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [177]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [178]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [181]:
arr_2d.shape

(3, 4)

In [179]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [180]:
np.flip(arr_2d,axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [182]:
np.flip(arr_2d,axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [186]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [187]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [188]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [191]:
x.reshape((1,-1))[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [193]:
x.reshape??

Docstring:
a.reshape(shape, order='C')

Returns an array containing the same data with a new shape.

Refer to `numpy.reshape` for full documentation.

See Also
--------
numpy.reshape : equivalent function

Notes
-----
Unlike the free function `numpy.reshape`, this method on `ndarray` allows
the elements of the shape parameter to be passed in as separate arguments.
For example, ``a.reshape(10, 11)`` is equivalent to
``a.reshape((10, 11))``.
Type:      builtin_function_or_method


In [194]:
def double(a):
    '''
    함수 사용법
    double(arr)
    '''
    return a*2

In [196]:
double??

Signature: double(a)
Source:   
def double(a):
    '''
    함수 사용법
    double(arr)
    '''
    return a*2
File:      c:\users\user\appdata\local\temp\ipykernel_432\3900343270.py
Type:      function
