# 1. What is Numpy?
<small>and how to use it? </small>

- numpy는 <b>"numerical python"</b>의 약자입니다.
> Numerical Computing : 컴퓨터가 실수값을 효과적으로 계산할 수 있도록 하는 연구 분야.
> Vector Arithmetic : 벡터 연산 --> 데이터가 벡터로 표현되기 때문이다.


- numpy는 다양한 머신러닝 라이브러리들에 의존성을 가지고 있고, 일반 파이썬 리스트에 비해 강력한 성능을 자랑합니다.
> 성능 : numpy array >> python list(or tuple) 


- python list와 비슷한 개념을 numpy에서는 **numpy array**라고 부른다.
> 파이썬 리스트처럼 여러 데이터를 한번에 다룰 수 있으나, 모든 데이터가 동일한 data type을 가져야합니다.


- C언어와 JAVA에서 사용하는 array와 비슷한 개념이며, 동적 할당(dynamic type binding)을 지원하는 파이썬의 리스트와 구조가 다릅니다.


- Numpy의 특징
<br>
<br>

**1) numpy array는 모든 원소의 자료형이 동일해야 한다.**

(아래는 numpy array가 지원하는 data types)

![numpy_data_type](../images/numpy/numpy_datatypes.png)

**2) numpy array는 선언할 때 크기를 지정한 뒤, 변경할 수 없다. list.append(), pop()을 통해 자유롭게 원소 변경 및 크기 변경이 가능하지만, numpy array는 만들어지고 나면 원소의 update는 가능하지만, array의 크기를 변경할 수는 없다.**

> numpy의 경우에는 append라는 함수가 있으나, 의미가 다릅니다.

> numpy array의 크기를 변경하는 경우에는 복사가 일어난다.

**3) 사실 numpy array는 C, C++로 구현이 되어 있다. 이는 high performance를 내기 위해서이며, python이 Numerical computing에 취약하다는 단점을 보완한다.**

(아래 예시는 C언어와 파이썬의 코드 비교)

```C
/* C 코드 */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

```python
# 파이썬 코드
result = 0
for i in range(100):
    result += i
```

**4) numpy array가 python list보다 빠른 이유 중에 하나는 원소의 type checking을 할 필요가 없기 때문이다.**

(아래 예시를 보자)

```C
/* C 코드 */
int x = 4;
x = "four";  // 실패
```
-> It is called, "Static type binding"



```python
# 파이썬 코드
x = 4
x = "four"
```

-> It is called, "Dynamic type binding"

(python list와 numpy array의 내부 구현 비교)

![Integer Memory Layout](../images/numpy/cint_vs_pyint.png)

![Array Memory Layout](../images/numpy/array_vs_list.png)

<small> (Source from Data Science Handbook) </small>

**5) numpy array는 universal function(through broadcast)를 제공하기 때문에 같은 연산 반복에 대해 훨씬 빠르다. 데이터의 크기가 클수록 차이가 더 크다.**

- 아래는 big_array라는 1000000개의 원소를 가지는 array를 만든 뒤에 for문을 돌면서 각 원소를 뒤집는 연산을 했을 때의 걸리는 시간과, numpy array에 있는 UFuncs(Universal function)을 사용했을 때 걸리는 시간을 측정한 것이다.


- 거의 1000배정도 차이가 나는 것을 볼 수 있다.

![speed_comparison](../images/numpy/list_vs_nparray.png)

# 2. Numpy Basics 

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

## 2.1 Numpy array Creation

In [2]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [3]:
# 파이썬 리스트 선언
data = [1, 2, 3, 4, 5]
data, type(data)

([1, 2, 3, 4, 5], list)

In [4]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
        ]
data2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
# 파이썬 list를 numpy array로 변환합니다.
arr1 = np.array(data)
print(type(arr1))
arr1, type(arr1) # numpy.ndarray : ndarray(n-dimensional array)
# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
#np.array([1, 2, 3, 4, 5]) # okay
#np.array((1, 2, 3, 4, 5)) # okay
arr1.shape # np.array.shape은 np.array의 크기를 알려줍니다.
# 5 x 1 (5, )

<class 'numpy.ndarray'>


(5,)

In [7]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2)
print(arr2)
print(type(arr2))
arr2.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


(3, 3)

In [ ]:
print("arr2의 ndim : ", arr2.ndim) # arr2의 차원
print("arr2의 shape : ", arr2.shape)# arr2의 행, 열의 크기
print("arr2의 size : ", arr2.size) # arr2의 행 x 열
print("arr2의 dtype : ", arr2.dtype) # arr2의 원소의 타입. # int64 : integer + 64bits
print("arr2의 itemsize : ", arr2.itemsize) # arr2의 원소의 사이즈(bytes) # 64bits = 8B
print("arr2의 nbytes : ", arr2.nbytes) # itemsize * size # numpy array가 차지하는 메모리 공간.

arr2의 ndim :  2
arr2의 shape :  (3, 3)
arr2의 size :  9
arr2의 dtype :  int64
arr2의 itemsize :  8
arr2의 nbytes :  72


## 2.2 Array Initialization 

- numpy array를 초기값과 함께 생성하는 방법도 있습니다.


- 원소가 0인 array를 생성하는 np.zeros()

- 원소가 1인 array를 생성하는 np.ones()

- 특정 범위의 원소를 가지는 np.arange()

In [ ]:
# 0이 5개 있는 array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# 0이 3x3인 array
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 1이 3개 있는 array
np.ones(3)

array([1., 1., 1.])

In [ ]:
# 1이 2x2인 array
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
# 0부터 9까지 숫자를 자동으로 생성한 array
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 10부터 99까지 숫자를 자동으로 생성한 array
np.arange(10, 100) # python range 함수와 동일한데, np.array 생성까지 자동으로 해줍니다.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

## 2.3. Array Operation (like vector) --> Universal Function

- numpy array를 쓰는 가장 큰 이유는 vector처럼 사용할 수 있기 때문입니다.
> e.g. arr1 = np.array([1, 2, 3, 4, 5]) --> (1, 2, 3, 4, 5) # vector

- 그렇기 때문에 scipy, matplotlib, scikit-learn, pandas, tensorflow, pytorch 등 대부분의 데이터분석 라이브러리들이 numpy array를 사용합니다.
> 대부분의 데이터 분석 라이브러리들은 벡터를 사용하는데, 그 벡터가 바로 numpy array로 표현되기 때문입니다.


- 데이터 분석은 99.9% 데이터를 벡터로 표현하여 분석하기 때문에, 이 특징은 ***굉장히*** 중요합니다.
> 벡터 == numpy array

![Vector operation](../images/numpy/vector_operations.png)

- 두 벡터 A = (1, 2), B = (2, 1)이라고 할 때, 벡터의 연산은 다음과 같이 정의됩니다.

A + B = (3, 3)


A - B = (-1, 1)


A o B = 1x2 + 2x1 = 4 (dot product)

![Vector product](../images/numpy/vector_product.png)

In [ ]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array((1, 2, 3))
v2 = np.array((4, 5, 6))
type(v1), type(v2)

(numpy.ndarray, numpy.ndarray)

In [ ]:
# 리스트로 더하기 연산해보기
t1 = (1, 2, 3)
t2 = (4, 5)
#type(t1), type(t2)
t1 + t2

(1, 2, 3, 4, 5)

In [ ]:
#  vector addition
v1 + v2

array([5, 7, 9])

In [ ]:
#  vector subtraction
v1 - v2

array([-3, -3, -3])

In [ ]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [ ]:
# (not vector operation) elementwise division
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [ ]:
# dot product
v1 @ v2 # 1x4 + 2x5 + 3x6 = 32

32

## 2.4. Broadcast

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [ ]:
arr1 = np.array([[1, 2, 3],
               [4, 5, 6]])

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr2 = np.array([7, 8, 9])

In [ ]:
arr2.shape

(3,)

In [ ]:
# 2개의 array를 더해보면?
arr1 + arr2 # [1, 2, 3] + [7, 8, 9] // [4, 5, 6] + [7, 8, 9]

array([[ 8, 10, 12],
       [11, 13, 15]])

In [ ]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2 # [1, 2, 3] * [7, 8, 9] // [4, 5, 6] * [7, 8, 9]
# [1, 2, 3]  X  [7]
# [4, 5, 6]     [8]
#               [9]

array([[ 7, 16, 27],
       [28, 40, 54]])

In [ ]:
# arr1에 10을 곱해보면?
arr1 * 10 # vector scalar multiplication

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# arr1을 제곱해보면?
arr1 * arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

## 2.5. Universal Functions 

- numpy array는 하나의 함수를 모든 원소에 자동으로 적용해주는 Universal Function이라는 기능을 제공한다. 이 덕분에 모든 원소에 대해 같은 작업을 처리할 때 엄청나게 빠른 속도를 낼 수 있다.

In [ ]:
arr1 = np.array([1, 2, 3])
arr1 = arr1 / 1
#arr1.dtype

In [ ]:
# 모든 원소를 역수를 취하려면 어떻게 해야할까?
1 / arr1 # 각 원소에 1 / 라는 operation을 모두 적용하는 연산이 됩니다.

array([1.        , 0.5       , 0.33333333])

In [ ]:
# 모든 원소에 2를 더하려면 어떻게 해야할까?
arr1 + 2

array([3., 4., 5.])

## 2.6. Indexing (same as python list, but more powerful) 

In [ ]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 첫번째 원소
arr1[0]

0

In [ ]:
# 마지막 원소
arr1[-1]

9

In [ ]:
# 앞에서부터 원소 3개 slicing
arr1[:3]

array([0, 1, 2])

In [8]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# arr2의 2, 3 원소 = 7
arr2[1, 2]

7

In [ ]:
# arr2의 세번째 columnm (3, 7, 11)
arr2[:, 2] # arr2에 있는 모든 row에 대해서 3번째 원소를 indexing --> numpy array
# arr2[0, 2]
# arr2[1, 2]
# arr2[2, 2]

array([ 3,  7, 11])

In [ ]:
# arr2의 두번째 row
#arr2[1]
arr2[1, :] # arr2에 있는 두번째 row에 대해서 모든 원소를 indexing --> numpy array

array([5, 6, 7, 8])

## 2.7. Masking 

In [ ]:
mask = np.array([1, 0, 0, 1, 1, 0, 0])
mask

array([1, 0, 0, 1, 1, 0, 0])

In [ ]:
data = np.random.randn(7, 4)
data

array([[ 1.92952526,  0.16811586, -0.54101152,  0.01775069],
       [-0.01501298, -0.49388391, -0.73565307,  0.07600854],
       [-0.01667803,  1.89936971, -0.04026871,  0.90275741],
       [ 2.02695639,  0.0905108 , -0.33656963, -0.44864434],
       [-0.05168743,  0.69968886, -1.85008029, -1.48106361],
       [ 0.53789872,  1.30805042,  1.27204837,  0.02936776],
       [ 0.82310049, -0.27940677, -0.8763139 , -0.474734  ]])

In [ ]:
data.shape

(7, 4)

In [ ]:
# mask 만들기
masked_data = (mask == 1)
masked_data

array([ True, False, False,  True,  True, False, False])

In [ ]:
# 위에서 생성한 data에 mask를 적용해본다.
data[masked_data, :]

array([[ 1.92952526,  0.16811586, -0.54101152,  0.01775069],
       [ 2.02695639,  0.0905108 , -0.33656963, -0.44864434],
       [-0.05168743,  0.69968886, -1.85008029, -1.48106361]])

In [ ]:
# 마스크를 0으로 바꿔본다.
data[mask == 0, :]

array([[-0.01501298, -0.49388391, -0.73565307,  0.07600854],
       [-0.01667803,  1.89936971, -0.04026871,  0.90275741],
       [ 0.53789872,  1.30805042,  1.27204837,  0.02936776],
       [ 0.82310049, -0.27940677, -0.8763139 , -0.474734  ]])

In [ ]:
# fancy indexing을 이용해서 masking
#data[:, 0] < 0
data[:, 0] < 0 # 7 x 1의 mask == 첫번째 column의 원소중에 0보다 작은 원소들의 위치가 True.

array([False,  True,  True, False,  True, False, False])

In [ ]:
# fancy indexing의 또 다른 방법
data[data[:, 0]<0, 0]

array([-0.01501298, -0.01667803, -0.05168743])

In [ ]:
data < 0

array([[False, False,  True, False],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [False, False,  True,  True],
       [ True, False,  True,  True],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [ ]:
data[data < 0] = 0 # 2차원 data에서 첫번째 column에 0보다 작은 원소들을 0으로 치환해주세요.
data

array([[1.92952526, 0.16811586, 0.        , 0.01775069],
       [0.        , 0.        , 0.        , 0.07600854],
       [0.        , 1.89936971, 0.        , 0.90275741],
       [2.02695639, 0.0905108 , 0.        , 0.        ],
       [0.        , 0.69968886, 0.        , 0.        ],
       [0.53789872, 1.30805042, 1.27204837, 0.02936776],
       [0.82310049, 0.        , 0.        , 0.        ]])

## 2.8. Numpy Methods 

In [ ]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
import numpy as np
mat1 = np.random.randn(5, 3)
mat1

array([[ 0.88158423,  1.03035424, -0.80172145],
       [-1.62479742,  0.57965347, -0.54298515],
       [ 0.72979378, -1.07112173,  0.984749  ],
       [ 0.58218058,  1.35036274, -0.10643136],
       [-0.05345354, -1.11696904,  0.25339134]])

In [ ]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[0.88158423, 1.03035424, 0.80172145],
       [1.62479742, 0.57965347, 0.54298515],
       [0.72979378, 1.07112173, 0.984749  ],
       [0.58218058, 1.35036274, 0.10643136],
       [0.05345354, 1.11696904, 0.25339134]])

In [ ]:
# mat1의 square root(제곱근) 구하기
comp1 = np.array(mat1, dtype=complex)
print(np.sqrt(comp1))
# imagnary numbers = nan

[[0.93892717+0.j         1.01506366+0.j         0.        +0.89538899j]
 [0.        +1.27467542j 0.76134977+0.j         0.        +0.73687526j]
 [0.85427969+0.j         0.        +1.03495011j 0.9923452 +0.j        ]
 [0.76300759+0.j         1.16205109+0.j         0.        +0.3262382j ]
 [0.        +0.23120021j 0.        +1.05686756j 0.50337992+0.j        ]]


In [ ]:
# mat1 제곱하기
np.square(mat1)

array([[0.77719076, 1.06162985, 0.64275728],
       [2.63996667, 0.33599814, 0.29483288],
       [0.53259897, 1.14730176, 0.96973059],
       [0.33893423, 1.82347952, 0.01132764],
       [0.00285728, 1.24761983, 0.06420717]])

In [ ]:
# mat1의 지수값 구하기
np.exp(mat1)

array([[2.41472216, 2.80205825, 0.44855613],
       [0.19695157, 1.78541961, 0.58101125],
       [2.07465274, 0.34262397, 2.67713984],
       [1.78993728, 3.85882502, 0.89903675],
       [0.94794998, 0.32727024, 1.28838738]])

In [ ]:
# mat의 log값(자연로그) 구하기
np.log(mat1)
# log의 밑이 음수가 될 수 없다. (자연로그)

<ipython-input-54-74a16559d825>:2: RuntimeWarning: invalid value encountered in log
  np.log(mat1)


array([[-0.12603472,  0.02990266,         nan],
       [        nan, -0.54532483,         nan],
       [-0.31499327,         nan, -0.01536849],
       [-0.5409746 ,  0.30037325,         nan],
       [        nan,         nan, -1.37282017]])

In [ ]:
# 상용로그
np.log10(mat1)

<ipython-input-55-a091af1a621d>:2: RuntimeWarning: invalid value encountered in log10
  np.log10(mat1)


array([[-0.05473619,  0.01298656,         nan],
       [        nan, -0.23683156,         nan],
       [-0.13679984,         nan, -0.00667445],
       [-0.23494228,  0.13045045,         nan],
       [        nan,         nan, -0.59620822]])

In [ ]:
# 이진로그
np.log2(mat1)

<ipython-input-56-09f0ec8234cb>:2: RuntimeWarning: invalid value encountered in log2
  np.log2(mat1)


array([[-0.18182967,  0.04314042,         nan],
       [        nan, -0.78673742,         nan],
       [-0.45443923,         nan, -0.02217205],
       [-0.78046138,  0.433347  ,         nan],
       [        nan,         nan, -1.98056085]])

In [ ]:
# 부호찾기
np.sign(mat1)

array([[ 1.,  1., -1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.]])

In [ ]:
# 올림
np.ceil(mat1)

array([[ 1.,  2., -0.],
       [-1.,  1., -0.],
       [ 1., -1.,  1.],
       [ 1.,  2., -0.],
       [-0., -1.,  1.]])

In [ ]:
# 내림
np.floor(mat1)

array([[ 0.,  1., -1.],
       [-2.,  0., -1.],
       [ 0., -2.,  0.],
       [ 0.,  1., -1.],
       [-1., -2.,  0.]])

In [ ]:
# 존재하지 않는 값이 있는지 없는지 # nan = not a number
np.isnan(mat1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.isnan(np.log(mat1))

<ipython-input-61-cb2ae9d6dc08>:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(mat1))


array([[False, False,  True],
       [ True, False,  True],
       [False,  True, False],
       [False, False,  True],
       [ True,  True, False]])

In [ ]:
np.isinf(mat1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.sin(mat1)

array([[ 0.77174731,  0.8574813 , -0.71855437],
       [-0.9985423 ,  0.54773404, -0.51669409],
       [ 0.66671595, -0.87773852,  0.8331333 ],
       [ 0.54984661,  0.97580274, -0.10623054],
       [-0.05342809, -0.89877577,  0.25068845]])

In [ ]:
np.cos(mat1)

array([[ 0.63592931,  0.51451513,  0.69547078],
       [-0.05397486,  0.83665251,  0.85617009],
       [ 0.74531191,  0.47913994,  0.55307225],
       [ 0.83526565,  0.21865274,  0.99434153],
       [ 0.9985717 ,  0.43840861,  0.96806782]])

In [ ]:
np.tan(mat1)

array([[ 1.21357404,  1.66658133, -1.03319131],
       [18.50013846,  0.65467328, -0.60349468],
       [ 0.89454623, -1.83190429,  1.50637335],
       [ 0.6582895 ,  4.46279671, -0.10683506],
       [-0.05350451, -2.05008695,  0.25895752]])

In [ ]:
np.tanh(mat1)

array([[ 0.70721209,  0.77405037, -0.66499806],
       [-0.9253171 ,  0.52241352, -0.49524429],
       [ 0.62293917, -0.78988346,  0.75511437],
       [ 0.52424851,  0.87413888, -0.1060313 ],
       [-0.05340268, -0.80651207,  0.24810392]])

In [ ]:
mat2 = np.random.randn(5, 3)
mat2

array([[ 1.44042289, -1.73145938, -0.84970036],
       [ 0.74355606, -0.00617509,  1.09774865],
       [-0.4881688 , -0.7886178 ,  0.70646718],
       [ 1.55966361,  0.13770618, -0.84233293],
       [-1.69189602,  0.33577668,  0.83816601]])

In [ ]:
np.maximum(mat1, mat2)

array([[ 1.44042289,  1.03035424, -0.80172145],
       [ 0.74355606,  0.57965347,  1.09774865],
       [ 0.72979378, -0.7886178 ,  0.984749  ],
       [ 1.55966361,  1.35036274, -0.10643136],
       [-0.05345354,  0.33577668,  0.83816601]])

## 2.9. Reshaping array

In [ ]:
x = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# x를 3x3 행렬로 변형합니다.
x1 = np.arange(1, 10).reshape(3, 3)
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x == x1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# (1, 2, 3)을 transpose 해봅니다.
x2 = np.array([1, 2, 3]).reshape(3, 1) # row vector -> column vector
x2

array([[1],
       [2],
       [3]])

## 2.10. Concatenation of arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# arr1와 arr2를 합칩니다
# arr1 + arr2?
np.concatenate([arr1, arr2])
#arr1 + arr2 # array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
# stacking vertically
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# stacking horizontally
np.hstack([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

## 2.11. Aggregation functions 

In [ ]:
mat1

array([[ 0.88158423,  1.03035424, -0.80172145],
       [-1.62479742,  0.57965347, -0.54298515],
       [ 0.72979378, -1.07112173,  0.984749  ],
       [ 0.58218058,  1.35036274, -0.10643136],
       [-0.05345354, -1.11696904,  0.25339134]])

In [ ]:
np.sum(mat1) # 15개 숫자의 총합.

1.074589685764616

In [ ]:
# 다른 축으로 더해보기
np.sum(mat1, axis=0) # column별 총합.

array([ 0.51530764,  0.77227967, -0.21299762])

In [ ]:
# 다른 축으로 더해보기
np.sum(mat1, axis=1) # row별 총합.

array([ 1.11021702, -1.58812911,  0.64342105,  1.82611195, -0.91703123])

In [ ]:
# 평균
np.mean(mat1)

0.07163931238430774

In [ ]:
mat3 = np.random.rand(5, 3)
mat3

array([[0.7277077 , 0.74442156, 0.62716276],
       [0.67426682, 0.40886693, 0.00351873],
       [0.54709935, 0.84446279, 0.1915848 ],
       [0.81677464, 0.26497683, 0.69736937],
       [0.29282502, 0.10515273, 0.69701789]])

In [ ]:
np.mean(mat3)

0.5095471954711476

In [ ]:
np.mean(mat3, axis=0)

array([0.61173471, 0.47357617, 0.44333071])

In [ ]:
np.mean(mat3, axis=1)

array([0.69976401, 0.36221749, 0.52771565, 0.59304028, 0.36499855])

In [ ]:
np.std(mat3) # 표준편차

0.2657988159041335

In [ ]:
np.min(mat3, axis=0)

array([0.29282502, 0.10515273, 0.00351873])

In [ ]:
np.max(mat3, axis=1)

array([0.74442156, 0.67426682, 0.84446279, 0.81677464, 0.69701789])

In [ ]:
# 최소값이 있는 Index
np.argmin(mat3, axis=0)

array([4, 4, 1])

In [ ]:
# 최대값이 있는 Index
np.argmax(mat3, axis=1)

array([1, 0, 1, 0, 2])

In [ ]:
np.cumsum(mat3)

array([0.7277077 , 1.47212926, 2.09929203, 2.77355884, 3.18242578,
       3.18594451, 3.73304386, 4.57750665, 4.76909145, 5.58586609,
       5.85084293, 6.54821229, 6.84103731, 6.94619004, 7.64320793])

In [ ]:
np.cumsum(mat3, axis=1) # row별 누적합.

array([[0.7277077 , 1.47212926, 2.09929203],
       [0.67426682, 1.08313375, 1.08665248],
       [0.54709935, 1.39156214, 1.58314694],
       [0.81677464, 1.08175147, 1.77912084],
       [0.29282502, 0.39797774, 1.09499564]])

In [ ]:
np.cumprod(mat3, axis=0)

array([[7.27707702e-01, 7.44421561e-01, 6.27162763e-01],
       [4.90669157e-01, 3.04369359e-01, 2.20681854e-03],
       [2.68444777e-01, 2.57028598e-01, 4.22792893e-04],
       [2.19258886e-01, 6.81066240e-02, 2.94842813e-04],
       [6.42044868e-02, 7.16159740e-03, 2.05510716e-04]])

In [ ]:
# 그냥 정렬
np.sort(mat3)

array([[0.62716276, 0.7277077 , 0.74442156],
       [0.00351873, 0.40886693, 0.67426682],
       [0.1915848 , 0.54709935, 0.84446279],
       [0.26497683, 0.69736937, 0.81677464],
       [0.10515273, 0.29282502, 0.69701789]])

In [ ]:
# index를 정렬
np.argsort(mat3, axis=0) # argument sorting에서 정렬된 값의 원래 위치를 보여줍니다.
# 정렬된 다음의 index를 원래 원소의 위치에 표시해줍니다.

array([[4, 4, 1],
       [2, 3, 2],
       [1, 1, 0],
       [0, 0, 4],
       [3, 2, 3]])

## 3. Powerful Numpy 

- 맨 처음에도 봤듯이 numpy는 파이썬 리스트에 비해 연산이 빠릅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [ ]:
np.random.seed(0)

def reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

def cum_sum(values):
    total = 0.0
    for num in values:
        total += num
    return total

In [ ]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 100, size=1000000)

In [ ]:
%timeit reverse_num(big_array)

2.35 s ± 99.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit 1.0 / big_array

1.47 ms ± 18.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%timeit cum_sum(big_array)

211 ms ± 2.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit np.sum(big_array)

736 µs ± 40.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Q. 왜 numpy가 파이썬(정확히는 CPython)으로 구현한 함수를 통해 반복문을 수행한것보다 빠를까?

A1. 매번 반복할 때마다 ***"type matching"*** 과 ***"function dispatching"*** 을 파이썬 interpreter가 수행하기 때문에 **"performance bottleneck"** 이 생깁니다.

A2.